### ISSUE TITLE
Why babel isn't a devDependency

### ISSUE THREAD

**Issue by notpushkin** [juice49/lipsumator#8]
WHY GOD WHY

**Comment by juice49** [comment]
Lipsumator is a bit old and needs some work. Babel is installed so that we can [use the polyfill](https://github.com/juice49/lipsumator/blob/master/src/index.js#L3), so it is in fact needed as a  production dependency.

The polyfill is nowadays published as a standalone npm module, so ideally we'd use that. It may not even be needed for node anymore as ES2015+ support has improved a lot since Lipsumator was first published.
